_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 100
disp_freq:
    value: 50
learning_rate:
    value: 0.0001
max_epoch:
    value: 100
momentum:
    value: 0.9
test_epoch:
    value: 1
weight_decay:
    value: 1e-05
